#include "main.h"

static const char* rome_numbers[5] = {"I", "II", "III", "VI", "V"};
enchanti bsmeta<enchanti>::elements[] = {{""},
{"accuracy"},
{"advise"},
{"charisma"},
{"climbing"},
{"cold"},
{"damage"},
{"dexterity"},
{"fire"},
{"fire resistance"},
{"healing"},
{"holyness"},
{"intellegence"},
{"invisibility"},
{"luck"},
{"magic resistance"},
{"neutralize poison"},
{"poison"},
{"poison resistance"},
{"protection"},
{"regeneration"},
{"sharpness"},
{"smashing"},
{"speed"},
{"strenght"},
{"vampirism"},
{"wizardy", rome_numbers},
};
assert_enum(enchant, OfWizardy);