#include "main.h"

static const char* rome_numbers[5] = {"I", "II", "III", "VI", "V"};
enchanti bsdata<enchanti>::elements[] = {{""},
{"accuracy"},
{"advise"},
{"cold"},
{"damage"},
{"energy drain"},
{"fear"},
{"fire"},
{"healing"},
{"holyness"},
{"invisibility"},
{"knowledge"},
{"luck"},
{"neutralize poison"},
{"paralize"},
{"poison"},
{"strong poison"},
{"protection"},
{"regeneration"},
{"sharpness"},
{"smashing"},
{"speed"},
{"strenght drain"},
{"vampirism"},
{"wizardy", rome_numbers},
};
assert_enum(enchant, OfWizardy);